server:
  port: 8080
  servlet:
    context-path: /stock-alarms/api/v1

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/stockalarms
    username: stockalarmsUser
    password: stockalarmsPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: stock-alarms
  resource: stock-alarms-be
  public-client: true

logging:
  level.root: info

stock-alarms:
  keycloak:
    credentials:
      client-id: realm-management
      secret: 47fe28fa-ea8c-4663-b497-cf6d710c10d9
